[package]
name = "bean_cypher"
version = "0.7.0"
edition = "2021"

[dependencies]
configparser = "3.1.0"
# color-eyre = "0.6.3"
egui = "0.34.3"
egui_extras = { version = "0.34.3", features = ["all_loaders"] }
eframe = { version = "0.34.3", features = [
    "default_fonts", # Embed the default egui fonts.
    "glow",          # Use the glow rendering backend. Alternative: "wgpu".
    "persistence",   # Enable restoring app state when restarting the app.
] }
rfd = "0.17.2"
serde = "1.0.228"
log = "0.4.27"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4.50"
web-sys = "0.3.70"              # to access the DOM (to hide the loading text)

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = { priority = -1, level = "deny" }
nursery = { priority = -1, level = "deny" }
unwrap_used = "deny"