[package]
name = "bean-cypher"
version = "0.4.0"
edition = "2021"

[dependencies]
configparser = "3.1.0"
color-eyre = "0.6.3"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
enum_glob_use = "deny"
pedantic = "deny"
nursery = "deny"
unwrap_used = "deny"